/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated.approvals'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated.activity'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated.vendors.index'
import { Route as AuthenticatedRfqsIndexRouteImport } from './routes/_authenticated.rfqs.index'
import { Route as AuthenticatedQuotationsIndexRouteImport } from './routes/_authenticated.quotations.index'
import { Route as AuthenticatedPurchaseOrdersIndexRouteImport } from './routes/_authenticated.purchase-orders.index'
import { Route as AuthenticatedVendorsNewRouteImport } from './routes/_authenticated.vendors.new'
import { Route as AuthenticatedVendorsIdRouteImport } from './routes/_authenticated.vendors.$id'
import { Route as AuthenticatedRfqsNewRouteImport } from './routes/_authenticated.rfqs.new'
import { Route as AuthenticatedRfqsIdRouteImport } from './routes/_authenticated.rfqs.$id'
import { Route as AuthenticatedPurchaseOrdersIdRouteImport } from './routes/_authenticated.purchase-orders.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedRfqsIdCompareRouteImport } from './routes/_authenticated.rfqs.$id.compare'
import { Route as AuthenticatedQuotationsRfqIdSubmitRouteImport } from './routes/_authenticated.quotations.$rfqId.submit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRfqsIndexRoute = AuthenticatedRfqsIndexRouteImport.update({
  id: '/rfqs/',
  path: '/rfqs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuotationsIndexRoute =
  AuthenticatedQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchaseOrdersIndexRoute =
  AuthenticatedPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVendorsNewRoute = AuthenticatedVendorsNewRouteImport.update({
  id: '/vendors/new',
  path: '/vendors/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorsIdRoute = AuthenticatedVendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRfqsNewRoute = AuthenticatedRfqsNewRouteImport.update({
  id: '/rfqs/new',
  path: '/rfqs/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRfqsIdRoute = AuthenticatedRfqsIdRouteImport.update({
  id: '/rfqs/$id',
  path: '/rfqs/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchaseOrdersIdRoute =
  AuthenticatedPurchaseOrdersIdRouteImport.update({
    id: '/purchase-orders/$id',
    path: '/purchase-orders/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRfqsIdCompareRoute =
  AuthenticatedRfqsIdCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedRfqsIdRoute,
  } as any)
const AuthenticatedQuotationsRfqIdSubmitRoute =
  AuthenticatedQuotationsRfqIdSubmitRouteImport.update({
    id: '/quotations/$rfqId/submit',
    path: '/quotations/$rfqId/submit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/rfqs/$id': typeof AuthenticatedRfqsIdRouteWithChildren
  '/rfqs/new': typeof AuthenticatedRfqsNewRoute
  '/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/vendors/new': typeof AuthenticatedVendorsNewRoute
  '/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/quotations/': typeof AuthenticatedQuotationsIndexRoute
  '/rfqs/': typeof AuthenticatedRfqsIndexRoute
  '/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/quotations/$rfqId/submit': typeof AuthenticatedQuotationsRfqIdSubmitRoute
  '/rfqs/$id/compare': typeof AuthenticatedRfqsIdCompareRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/rfqs/$id': typeof AuthenticatedRfqsIdRouteWithChildren
  '/rfqs/new': typeof AuthenticatedRfqsNewRoute
  '/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/vendors/new': typeof AuthenticatedVendorsNewRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/quotations': typeof AuthenticatedQuotationsIndexRoute
  '/rfqs': typeof AuthenticatedRfqsIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/quotations/$rfqId/submit': typeof AuthenticatedQuotationsRfqIdSubmitRoute
  '/rfqs/$id/compare': typeof AuthenticatedRfqsIdCompareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/_authenticated/rfqs/$id': typeof AuthenticatedRfqsIdRouteWithChildren
  '/_authenticated/rfqs/new': typeof AuthenticatedRfqsNewRoute
  '/_authenticated/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/_authenticated/vendors/new': typeof AuthenticatedVendorsNewRoute
  '/_authenticated/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/_authenticated/quotations/': typeof AuthenticatedQuotationsIndexRoute
  '/_authenticated/rfqs/': typeof AuthenticatedRfqsIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/_authenticated/quotations/$rfqId/submit': typeof AuthenticatedQuotationsRfqIdSubmitRoute
  '/_authenticated/rfqs/$id/compare': typeof AuthenticatedRfqsIdCompareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/activity'
    | '/approvals'
    | '/reports'
    | '/settings'
    | '/admin/users'
    | '/purchase-orders/$id'
    | '/rfqs/$id'
    | '/rfqs/new'
    | '/vendors/$id'
    | '/vendors/new'
    | '/purchase-orders/'
    | '/quotations/'
    | '/rfqs/'
    | '/vendors/'
    | '/quotations/$rfqId/submit'
    | '/rfqs/$id/compare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/activity'
    | '/approvals'
    | '/reports'
    | '/settings'
    | '/'
    | '/admin/users'
    | '/purchase-orders/$id'
    | '/rfqs/$id'
    | '/rfqs/new'
    | '/vendors/$id'
    | '/vendors/new'
    | '/purchase-orders'
    | '/quotations'
    | '/rfqs'
    | '/vendors'
    | '/quotations/$rfqId/submit'
    | '/rfqs/$id/compare'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_authenticated/activity'
    | '/_authenticated/approvals'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/admin/users'
    | '/_authenticated/purchase-orders/$id'
    | '/_authenticated/rfqs/$id'
    | '/_authenticated/rfqs/new'
    | '/_authenticated/vendors/$id'
    | '/_authenticated/vendors/new'
    | '/_authenticated/purchase-orders/'
    | '/_authenticated/quotations/'
    | '/_authenticated/rfqs/'
    | '/_authenticated/vendors/'
    | '/_authenticated/quotations/$rfqId/submit'
    | '/_authenticated/rfqs/$id/compare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rfqs/': {
      id: '/_authenticated/rfqs/'
      path: '/rfqs'
      fullPath: '/rfqs/'
      preLoaderRoute: typeof AuthenticatedRfqsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotations/': {
      id: '/_authenticated/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof AuthenticatedQuotationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchase-orders/': {
      id: '/_authenticated/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/new': {
      id: '/_authenticated/vendors/new'
      path: '/vendors/new'
      fullPath: '/vendors/new'
      preLoaderRoute: typeof AuthenticatedVendorsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/$id': {
      id: '/_authenticated/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof AuthenticatedVendorsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rfqs/new': {
      id: '/_authenticated/rfqs/new'
      path: '/rfqs/new'
      fullPath: '/rfqs/new'
      preLoaderRoute: typeof AuthenticatedRfqsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rfqs/$id': {
      id: '/_authenticated/rfqs/$id'
      path: '/rfqs/$id'
      fullPath: '/rfqs/$id'
      preLoaderRoute: typeof AuthenticatedRfqsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchase-orders/$id': {
      id: '/_authenticated/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rfqs/$id/compare': {
      id: '/_authenticated/rfqs/$id/compare'
      path: '/compare'
      fullPath: '/rfqs/$id/compare'
      preLoaderRoute: typeof AuthenticatedRfqsIdCompareRouteImport
      parentRoute: typeof AuthenticatedRfqsIdRoute
    }
    '/_authenticated/quotations/$rfqId/submit': {
      id: '/_authenticated/quotations/$rfqId/submit'
      path: '/quotations/$rfqId/submit'
      fullPath: '/quotations/$rfqId/submit'
      preLoaderRoute: typeof AuthenticatedQuotationsRfqIdSubmitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRfqsIdRouteChildren {
  AuthenticatedRfqsIdCompareRoute: typeof AuthenticatedRfqsIdCompareRoute
}

const AuthenticatedRfqsIdRouteChildren: AuthenticatedRfqsIdRouteChildren = {
  AuthenticatedRfqsIdCompareRoute: AuthenticatedRfqsIdCompareRoute,
}

const AuthenticatedRfqsIdRouteWithChildren =
  AuthenticatedRfqsIdRoute._addFileChildren(AuthenticatedRfqsIdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedPurchaseOrdersIdRoute: typeof AuthenticatedPurchaseOrdersIdRoute
  AuthenticatedRfqsIdRoute: typeof AuthenticatedRfqsIdRouteWithChildren
  AuthenticatedRfqsNewRoute: typeof AuthenticatedRfqsNewRoute
  AuthenticatedVendorsIdRoute: typeof AuthenticatedVendorsIdRoute
  AuthenticatedVendorsNewRoute: typeof AuthenticatedVendorsNewRoute
  AuthenticatedPurchaseOrdersIndexRoute: typeof AuthenticatedPurchaseOrdersIndexRoute
  AuthenticatedQuotationsIndexRoute: typeof AuthenticatedQuotationsIndexRoute
  AuthenticatedRfqsIndexRoute: typeof AuthenticatedRfqsIndexRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
  AuthenticatedQuotationsRfqIdSubmitRoute: typeof AuthenticatedQuotationsRfqIdSubmitRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedPurchaseOrdersIdRoute: AuthenticatedPurchaseOrdersIdRoute,
  AuthenticatedRfqsIdRoute: AuthenticatedRfqsIdRouteWithChildren,
  AuthenticatedRfqsNewRoute: AuthenticatedRfqsNewRoute,
  AuthenticatedVendorsIdRoute: AuthenticatedVendorsIdRoute,
  AuthenticatedVendorsNewRoute: AuthenticatedVendorsNewRoute,
  AuthenticatedPurchaseOrdersIndexRoute: AuthenticatedPurchaseOrdersIndexRoute,
  AuthenticatedQuotationsIndexRoute: AuthenticatedQuotationsIndexRoute,
  AuthenticatedRfqsIndexRoute: AuthenticatedRfqsIndexRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
  AuthenticatedQuotationsRfqIdSubmitRoute:
    AuthenticatedQuotationsRfqIdSubmitRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
